SELECT * FROM TRANS_PENJUALAN
SELECT * FROM CHECKOUT
SELECT * FROM JURNAL



UPDATE TRANS_PENJUALAN
SET TANGGAL = '2021-07-25',
TANGGAL_BAYAR = '2021-07-26',
TANGGAL_TERKIRIM = '2021-07-26',
TANGGAL_TERIMA = '2021-07-29'
WHERE TRANS_PENJUALAN_ID = 20073

UPDATE JURNAL
SET TANGGAL = '2021-07-26'
WHERE TRANS_PENJUALAN_ID = 20073


UPDATE TRANS_PENJUALAN
SET TANGGAL = DATEADD(MONTH, 1, TANGGAL),
TANGGAL_BAYAR = DATEADD(MONTH, 1, TANGGAL_BAYAR),
TANGGAL_TERKIRIM = DATEADD(MONTH, 1, TANGGAL_TERKIRIM),
TANGGAL_TERIMA = DATEADD(MONTH, 1, TANGGAL_TERIMA)


update JURNAL
SET TANGGAL = DATEADD(MONTH, 1, TANGGAL)
where TRANS_PENJUALAN_ID  is not null
