//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public CART()
        {
            this.PEMBAYARANs = new HashSet<PEMBAYARAN>();
        }
    
        public long CART_ID { get; set; }
        public long REF_USER_ID { get; set; }
        public long PROD_ID { get; set; }
        public int AMMOUNT { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual REF_USER REF_USER { get; set; }
        public virtual ICollection<PEMBAYARAN> PEMBAYARANs { get; set; }
    }
}
