//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKOUT
    {
        public long CHECKOUT_ID { get; set; }
        public Nullable<long> PROD_ID { get; set; }
        public Nullable<long> TRANS_PENJUALAN_ID { get; set; }
        public Nullable<int> JUMLAH_BARANG { get; set; }
        public Nullable<decimal> HARGA_PRODUK { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual TRANS_PENJUALAN TRANS_PENJUALAN { get; set; }
    }
}
