//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.CARTs = new HashSet<CART>();
            this.CHECKOUTs = new HashSet<CHECKOUT>();
            this.TRANS_STOCK_BARANG = new HashSet<TRANS_STOCK_BARANG>();
        }
    
        public long PROD_ID { get; set; }
        public string PROD_NAME { get; set; }
        public string PROD_NO { get; set; }
        public decimal PRICE { get; set; }
        public int STOCK_TOTAL { get; set; }
        public string FOTO { get; set; }
        public Nullable<int> BERAT_PRODUK { get; set; }
        public string IS_ACTIVE { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual ICollection<CHECKOUT> CHECKOUTs { get; set; }
        public virtual ICollection<TRANS_STOCK_BARANG> TRANS_STOCK_BARANG { get; set; }
    }
}
