//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_STOCK_BARANG
    {
        public TRANS_STOCK_BARANG()
        {
            this.JURNALs = new HashSet<JURNAL>();
        }
    
        public long TRANS_STOCK_BARANG_ID { get; set; }
        public string TRANS_NO { get; set; }
        public Nullable<long> PROD_ID { get; set; }
        public Nullable<long> SUPPLIER_ID { get; set; }
        public int STOCK_AMT { get; set; }
        public Nullable<decimal> HARGA { get; set; }
        public System.DateTime TANGGAL { get; set; }
    
        public virtual ICollection<JURNAL> JURNALs { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
