//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_HUTANG
    {
        public TRANS_HUTANG()
        {
            this.JURNALs = new HashSet<JURNAL>();
            this.TRANS_PEMBAYARAN_HUTANG = new HashSet<TRANS_PEMBAYARAN_HUTANG>();
        }
    
        public long TRANS_HUTANG_ID { get; set; }
        public Nullable<long> CLIENT_ID { get; set; }
        public string TRANS_NO { get; set; }
        public Nullable<decimal> HUTANG_AMT { get; set; }
        public string IS_ACTIVE { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public Nullable<decimal> SISA { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual ICollection<JURNAL> JURNALs { get; set; }
        public virtual ICollection<TRANS_PEMBAYARAN_HUTANG> TRANS_PEMBAYARAN_HUTANG { get; set; }
    }
}
