//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_PENJUALAN
    {
        public TRANS_PENJUALAN()
        {
            this.CHECKOUTs = new HashSet<CHECKOUT>();
            this.JURNALs = new HashSet<JURNAL>();
        }
    
        public long TRANS_PENJUALAN_ID { get; set; }
        public string TRANS_NO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public System.DateTime TANGGAL { get; set; }
        public string STATUS { get; set; }
        public decimal HARGA_ONGKIR { get; set; }
        public long REF_USER_ID { get; set; }
        public string ALAMAT { get; set; }
        public string NAMA_PENERIMA { get; set; }
        public string ONGKIR_NAMA { get; set; }
        public string ONGKIR_TYPE { get; set; }
        public string BUKTI_TRANSAKSI { get; set; }
        public Nullable<System.DateTime> TANGGAL_TERKIRIM { get; set; }
        public string RESI_PENGIRIMAN { get; set; }
        public Nullable<System.DateTime> TANGGAL_BAYAR { get; set; }
        public Nullable<System.DateTime> TANGGAL_TERIMA { get; set; }
        public Nullable<int> PLACE_ID { get; set; }
        public string BUKTI_REFUND { get; set; }
        public string NOTES { get; set; }
        public string PHONE_NUMBER { get; set; }
    
        public virtual ICollection<CHECKOUT> CHECKOUTs { get; set; }
        public virtual ICollection<JURNAL> JURNALs { get; set; }
        public virtual REF_USER REF_USER { get; set; }
    }
}
