//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_BIAYA
    {
        public TRANS_BIAYA()
        {
            this.JURNALs = new HashSet<JURNAL>();
        }
    
        public long TRANS_BIAYA_ID { get; set; }
        public string TRANS_NO { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> AMT { get; set; }
        public System.DateTime TANGGAL { get; set; }
    
        public virtual ICollection<JURNAL> JURNALs { get; set; }
    }
}
