//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.TRANS_HUTANG = new HashSet<TRANS_HUTANG>();
        }
    
        public long CLIENT_ID { get; set; }
        public string CLIENT_NO { get; set; }
        public string CLIENT_NAME { get; set; }
    
        public virtual ICollection<TRANS_HUTANG> TRANS_HUTANG { get; set; }
    }
}
