//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE
    {
        public int CITY_ID { get; set; }
        public string PROVINCE { get; set; }
        public string TYPE { get; set; }
        public string CITY_NAME { get; set; }
        public string POSTAL_CODE { get; set; }
    }
}
