//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REF_USER
    {
        public REF_USER()
        {
            this.CARTs = new HashSet<CART>();
            this.TRANS_PENJUALAN = new HashSet<TRANS_PENJUALAN>();
        }
    
        public long REF_USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string ROLE { get; set; }
        public System.DateTime DTM_CRT { get; set; }
        public System.DateTime DTM_UPD { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual ICollection<TRANS_PENJUALAN> TRANS_PENJUALAN { get; set; }
    }
}
