//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkripsiIanKeefe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        public SUPPLIER()
        {
            this.TRANS_STOCK_BARANG = new HashSet<TRANS_STOCK_BARANG>();
        }
    
        public long SUPPLIER_ID { get; set; }
        public string SUPPLIER_NO { get; set; }
        public string SUPPLIER_NAME { get; set; }
    
        public virtual ICollection<TRANS_STOCK_BARANG> TRANS_STOCK_BARANG { get; set; }
    }
}
