UPDATE TRANS_PENJUALAN 
SET 
NOTES = NULL,
BUKTI_TRANSAKSI  = NULL,
RESI_PENGIRIMAN = NULL,
BUKTI_REFUND = NULL

SELECT DISTINCT J.* FROM JURNAL J
JOIN TRANS_PENJUALAN TP ON J.TRANS_PENJUALAN_ID = J.TRANS_PENJUALAN_ID
 WHERE J.TRANS_PENJUALAN_ID IS NOT NULL

 SELECT * FROM TRANS_PENJUALAN 

  SELECT * FROM JURNAL  WHERE TRANS_PENJUALAN_ID IS NOT NULL   WHERE TRANS_PENJUALAN_ID = 20114

DELETE FROM JURNAL WHERE COA_ID IS NULL

ALTER TABLE JURNAL
ALTER COLUMN DESCR VARCHAR(255) NULL

select * from TRANS_PENJUALAN WHERE TANGGAL >= '2021-1-1' ORDER BY TANGGAL

