SELECT FORMAT(DTM_CRT,'MM-yyyy') FROM AGRMNT WHERE DTM_CRT >= DATEADD(MONTH, -12,DATEADD(DAY, 1, EOMONTH(GETDATE(),-1)))


SELECT YEAR(DTM_CRT) AS YEAR,  MONTH(DTM_CRT) AS MONTH, COUNT(AGRMNT_ID) 
FROM AGRMNT 
where DTM_CRT >= DATEADD(MONTH, -12,DATEADD(DAY, 1, EOMONTH(GETDATE(),-1)))
GROUP BY YEAR(DTM_CRT), MONTH(DTM_CRT) 
ORDER BY YEAR(DTM_CRT), MONTH(DTM_CRT) 



SELECT count(agrmnt_id) FROM AGRMNT 

select FORMAT(DATEADD(month, -12, GETDATE()), 'MM-yyyy')


SELECT DATEADD(DAY,  1, EOMONTH(GETDATE(),-1))

SELECT EOMONTH(DATEADD(MONTH, -12, getdate()),-1)


SELECT DATEADD(month,  DATEDIFF(month, 0, GETDATE()),0) AS StartOfMonth

SELECT DATEADD(MONTH, -12,DATEADD(DAY, 1, EOMONTH(GETDATE(),-1)))

SELECT DATEDIFF (MONTH, 0, GETDATE())