INSERT INTO TRANS_PENJUALAN
VALUES ('100', 200, GETDATE(), 'M', 1, 100, 5)

SELECT * FROM TRANS_PENJUALAN

SELECT * FROM ONGKIR

INSERT INTO ONGKIR
VALUES ('JNE', 1)

INSERT INTO ONGKIR_TYPE
VALUES ('Instant')

SELECT * FROM PRODUCT

SELECT * FROM CHECKOUT

INSERT INTO CHECKOUT
VALUES (2,2, 12)

INSERT INTO PRODUCT
VALUES ('Garnier Neril Hair Tonic Shampoo', '200', 30000, 12, 12)

UPDATE TRANS_PENJUALAN
SET STATUS = ''

DELETE FROM TRANS_PENJUALAN
WHERE TRANS_PENJUALAN_ID = 3