CREATE TABLE REF_USER
(REF_USER_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
USERNAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255),
PHONE_NUMBER VARCHAR(255),
ROLE VARCHAR(255) NOT NULL,
ADDR VARCHAR(255),
DTM_CRT DATETIME NOT NULL,
DTM_UPD DATETIME NOT NULL,
EMAIL VARCHAR(255) NOT NULL
)

drop table ONGKIR

SELECT * FROM REF_USER


ALTER TABLE REF_USER
	ADD EMAIL VARCHAR(255) NOT NULL


INSERT INTO REF_USER(username, PASSWORD,FIRST_NAME, ROLE, DTM_CRT, DTM_UPD, EMAIL)
VALUES ('admin', 'laisontrading', 'AD','Admin', GETDATE(), GETDATE(), 'andy.apriliandi@gmail.com')

UPDATE REF_USER
SET FIRST_NAME = 'Admin',
ROLE='AD'

DELETE FROM REF_USER
WHERE REF_USER_ID = 3

CREATE TABLE PRODUCT
(PROD_ID bigint identity not null PRIMARY KEY,
PROD_NAME VARCHAR(255) NOT NULL,
PROD_NO VARCHAR(255)  NOT NULL,
PRICE DECIMAL(9,2) NOT NULL,
STOCK_TOTAL INT NOT NULL,
FOTO VARBINARY(MAX) NOT NULL )

select * from product

CREATE TABLE CART
(CART_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
REF_USER_ID BIGINT NOT NULL ,
PROD_ID BIGINT NOT NULL FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID),
FOREIGN KEY (REF_USER_ID) REFERENCES REF_USER (REF_USER_ID)
)

SELECT * FROM CART


CREATE TABLE CLIENT
(CLIENT_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
CLIENT_NO VARCHAR(255) NOT NULL,
CLIENT_NAME VARCHAR(255) NOT NULL
)

CREATE TABLE ONGKIR_TYPE
(ONGKIR_TYPE_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
ONGKIR_TYPE_NAME VARCHAR(255) NOT NULL
)

CREATE TABLE ONGKIR
(ONGKIR_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
ONGKIR_NAME VARCHAR(255) NOT NULL,
ONGKIR_TYPE_ID BIGINT NOT NULL FOREIGN KEY(ONGKIR_TYPE_ID) REFERENCES ONGKIR_TYPE(ONGKIR_TYPE_ID)
)

SELECT * FROM ONGKIR

CREATE TABLE COA
(COA_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
COA_NO VARCHAR(255) NOT NULL
)

CREATE TABLE SUPPLIER
(
SUPPLIER_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
SUPPLIER_NO VARCHAR(255) NOT NULL,
SUPPLIER_NAME VARCHAR(255) NOT NULL
)

CREATE TABLE TRANS_BIAYA
(
	TRANS_BIAYA_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	TRANS_NO VARCHAR(255) NOT NULL,
	DESCR VARCHAR(255) NOT NULL,
	AMT DECIMAL(9,2) NOT NULL,
	TANGGAL DATETIME NOT NULL
)

SELECT * FROM TRANS_PEMBAYARAN_HUTANG

select * from TRANS_HUTANG

UPDATE TRANS_HUTANG
SET IS_ACTIVE = 'ACT'

select * from CLIENT

SELECT * FROM PRODUCT

select * from SUPPLIER

SELECT * FROM TRANS_PEMBAYARAN_HUTANG



INSERT INTO TRANS_PEMBAYARAN_HUTANG
VALUES (1, 500, 400000, GETDATE())

INSERT INTO TRANS_STOCK_BARANG
VALUES (304, 2, 1, 12, 20000.00, GETDATE())




insert into TRANS_BIAYA
values('102', 'BP', 30000, GETDATE())

CREATE TABLE STOCK_AKHIR
(
STOCK_AKHIR_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
PROD_ID BIGINT NOT NULL FOREIGN KEY(PROD_ID) REFERENCES  PRODUCT(PROD_ID),
STOCK_AKHIR INT NOT NULL,
DTM_CRT DATETIME NOT NULL,
DTM_UPD DATETIME NOT NULL
)


CREATE TABLE TRANS_PENJUALAN
(
TRANS_PENJUALAN_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
TRANS_NO VARCHAR(255) NOT NULL,
TOTAL DECIMAL(9,2) NOT NULL,
TANGGAL DATETIME NOT NULL,
STATUS VARCHAR(255) NOT NULL,
ONGKIR_ID BIGINT FOREIGN KEY(ONGKIR_ID) REFERENCES ONGKIR (ONGKIR_ID),
HARGA_ONGKIR DECIMAL(9,2) NOT NULL,
REF_USER_ID BIGINT NOT NULL FOREIGN KEY (REF_USER_ID) REFERENCES REF_USER(REF_USER_ID)
)

DROP TABLE TRANS_PENJUALAN

SELECT *FROM TRANS_PENJUALAN

ALTER TABLE CHECKOUT
ADD HARGA_PRODUK DECIMAL(9,2)

SELECT * FROM TRANS_BIAYA

UPDATE PRODUCT
SET BERAT_PRODUK = 0.8

SELECT * FROM PRODUCT

ALTER TABLE PRODUCT
ALTER COLUMN BERAT_PRODUK  DECIMAL(9,2)

ALTER TABLE TRANS_HUTANG
ALTER COLUMN IS_ACTIVE Varchar(255)

CREATE TABLE CHECKOUT
(
	CHECKOUT_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	PROD_ID BIGINT FOREIGN KEY(PROD_ID) REFERENCES PRODUCT (PROD_ID),
	TRANS_PENJUALAN_ID BIGINT FOREIGN KEY(TRANS_PENJUALAN_ID) REFERENCES TRANS_PENJUALAN (TRANS_PENJUALAN_ID),
	JUMLAH_BARANG INT
)

DROP TABLE CHECKOUT


CREATE TABLE TRANS_STOCK_BARANG
(
	TRANS_STOCK_BARANG_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	TRANS_NO VARCHAR(255) NOT NULL,
	PROD_ID BIGINT FOREIGN KEY(PROD_ID) REFERENCES PRODUCT (PROD_ID),
	SUPPLIER_ID BIGINT FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIER (SUPPLIER_ID),
	STOCK_AMT INT NOT NULL,
	HARGA DECIMAL(9,2) NOT NULL,
	TANGGAL DATETIME NOT NULL
)

CREATE TABLE TRANS_HUTANG
(
	TRANS_HUTANG_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	CLIENT_ID BIGINT FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
	TRANS_NO VARCHAR(255) NOT NULL,
	HUTANG_AMT DECIMAL(9,2) NOT NULL,
	IS_ACTIVE INT NOT NULL,
	TANGGAL DATETIME NOT NULL,
	SISA DECIMAL(9,2) NOT NULL
)

CREATE TABLE TRANS_PEMBAYARAN_HUTANG
(
	TRANS_BYR_UTANG_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	TRANS_HUTANG_ID BIGINT FOREIGN KEY (TRANS_HUTANG_ID) REFERENCES TRANS_HUTANG (TRANS_HUTANG_ID),
	TRANS_NO VARCHAR(255) NOT NULL,
	TOTAL DECIMAL(9,2) NOT NULL,
	TANGGAL DATETIME NOT NULL
)

CREATE TABLE JURNAL
(
	JURNAL_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
	TRANS_PENJUALAN_ID BIGINT FOREIGN KEY (TRANS_PENJUALAN_ID) REFERENCES TRANS_PENJUALAN (TRANS_PENJUALAN_ID),
	TRANS_HUTANG_ID BIGINT FOREIGN KEY (TRANS_HUTANG_ID) REFERENCES TRANS_HUTANG (TRANS_HUTANG_ID),
	TRANS_BIAYA_ID BIGINT FOREIGN KEY (TRANS_BIAYA_ID) REFERENCES TRANS_BIAYA (TRANS_BIAYA_ID),
	TRANS_BYR_UTANG_ID BIGINT FOREIGN KEY(TRANS_BYR_UTANG_ID) REFERENCES TRANS_PEMBAYARAN_HUTANG (TRANS_BYR_UTANG_ID),
	TRANS_STOCK_BARANG_ID BIGINT FOREIGN KEY (TRANS_STOCK_BARANG_ID) REFERENCES TRANS_STOCK_BARANG (TRANS_STOCK_BARANG_ID),
	COA_ID BIGINT NOT NULL FOREIGN KEY (COA_ID) REFERENCES COA(COA_ID),
	IN_AMT DECIMAL(9,2) NOT NULL,
	OUT_AMT DECIMAL(9,2) NOT NULL,
	DESCR VARCHAR(255)NOT NULL
)

